export const EligibleUser = [
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176443",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    image: "https://github.com/shadcn.png",
    assigned: [
      { title: "Facility", active: true },
      { title: "Schedule", active: true },
      { title: "Facilitator", active: true },
    ],
    status: true,
  },
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176442",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    status: true,
    assigned: [
      { title: "Facility", active: true },
      { title: "Schedule", active: false },
      { title: "Facilitator", active: true },
    ],
    image: "https://github.com/shadcn.png",
  },
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176444",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    image: "https://github.com/shadcn.png",
    status: true,
    assigned: [
      { title: "Facility", active: false },
      { title: "Schedule", active: false },
      { title: "Facilitator", active: false },
    ],
  },
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176441",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    image: "https://github.com/shadcn.png",
    status: true,
    assigned: [
      { title: "Facility", active: false },
      { title: "Schedule", active: true },
      { title: "Facilitator", active: false },
    ],
  },
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176446",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    image: "https://github.com/shadcn.png",
    status: true,
    assigned: [
      { title: "Facility", active: true },
      { title: "Schedule", active: false },
      { title: "Facilitator", active: true },
    ],
  },
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176452",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    image: "https://github.com/shadcn.png",
    status: true,
    assigned: [
      { title: "Facility", active: true },
      { title: "Schedule", active: true },
      { title: "Facilitator", active: false },
    ],
  },
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76196443",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    image: "https://github.com/shadcn.png",
    status: true,
    assigned: [
      { title: "Facility", active: true },
      { title: "Schedule", active: true },
      { title: "Facilitator", active: true },
    ],
  },
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176486",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    image: "https://github.com/shadcn.png",
    status: true,
    assigned: [
      { title: "Facility", active: true },
      { title: "Schedule", active: true },
      { title: "Facilitator", active: true },
    ],
  },
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176123",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    image: "https://github.com/shadcn.png",
    status: true,
    assigned: [
      { title: "Facility", active: true },
      { title: "Schedule", active: true },
      { title: "Facilitator", active: true },
    ],
  },
  {
    id: "9953ed85-31a0-4db9-acc8-e25b76176749",
    userName: "Dipipi Rayamajhi",
    units: "7 of 7",
    approved: "5",
    via: "Email",
    email_data: "04/20/2014",
    message: "The message was delivered to the students",
    course: "Diploma It",
    placement_date: "April 13,2021",
    submitted_date: "April 9,2021",
    submitted_documents: ["Passport", "Covid Report", "Police Report"],
    image: "https://github.com/shadcn.png",
    status: true,
    assigned: [
      { title: "Facility", active: true },
      { title: "Schedule", active: true },
      { title: "Facilitator", active: true },
    ],
  },
];
